image: "rust:latest"

stages:
  - "test"
  - "build"
  - "publish"

# Prepare
.prepare_stable:
  script:
    - echo 'Running stable preparation...'
    - rustup update
    - rustup default > .toolchain
  cache:
    - key:
        files:
          - "Cargo.lock"
      paths:
        - target

.prepare_nightly:
  script:
    - echo 'Running nightly preparation...'
    - rustup install nightly
    - rustup default nightly
    - rustup default > .toolchain
  cache:
    - key:
        files:
          - "Cargo.lock"
      paths:
        - target

# Test
test_stable:
  stage: "test"
  extends: ".prepare_stable"
  script:
    - echo 'Running stable checks...'
    - cargo check
    - echo 'Running stable tests...'
    - cargo test
    - echo 'Running stable clippy...'
    - rustup component add clippy-preview
    - cargo clippy

test_nightly:
  stage: "test"
  extends: ".prepare_nightly"
  script:
    - echo 'Running nightly checks...'
    - cargo check
    - echo 'Running nightly tests...'
    - cargo test
    - echo 'Running nightly clippy...'
    - rustup component add clippy-preview
    - cargo clippy

# Build
build_stable:
  stage: "build"
  extends: ".prepare_stable"
  needs:
    - "test_stable"
  script:
    - echo 'Building stable release...'
    - cargo build --release
  artifacts:
    name: "kyanite"
    paths:
      - "target/release/kyanite"

build_nightly:
  stage: "build"
  extends: ".prepare_nightly"
  needs:
    - "test_nightly"
  script:
    - echo 'Building nightly release...'
    - cargo build --release

# Publish
crates_io:
  stage: "publish"
  needs:
    - "build_stable"
  script:
    - echo 'Publishing to crates.io...'
    - cargo publish --token "$CRATES_IO_API_TOKEN"
  only:
    - tags@lu-ci/kyanite
